apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: py-func
    apps.tanzu.vmware.com/workload-type: web
  name: py-func
spec:
  build:
    env:
    - name: BP_FUNCTION
      value: func.main
